---
title: "Getters and Setters"
output: 
  html_document:
    number_sections: true
    toc: true
pkgdown:
  as_is: true
vignette: >
  %\VignetteIndexEntry{Getters and Setters}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

*Giotto* stores information in different [slots](https://giotto-suite.github.io/Giotto_website/articles/articles/structure.html#giotto-object-structure), which can be accessed through these getters and setters functions. They can be found in the [`accessors.R`](https://github.com/giotto-suite/Giotto/blob/suite/R/accessors.R) file.

`setGiotto()`: Sets any *Giotto* subobject

`getCellMetadata()`: Gets cell metadata

`setCellMetadata()`: Sets cell metadata

`getFeatureMetadata()`: Gets feature metadata

`getFeatureMetadata()`: Sets feature metadata

`getExpression()`: To select the expression matrix to use

`setExpression()`: Sets a new expression matrix to the expression slot

`getSpatialLocations()`: Get spatial locations to use

`setSpatialLocations()`: Sets new spatial locations

`getDimReduction()`: To select the dimension reduction values to use

`setDimReduction()`: Sets new dimension reduction object

`getNearestNetwork()`: To select the nearest neighbor network (kNN or
sNN) to use

`setNearestNetwork()`: Sets a new nearest neighbor network (kNN or sNN)

`getSpatialNetwork()`: To select the spatial network to use

`setSpatialNetwork()`: Sets a new spatial network

`getPolygonInfo()`: Gets spatial polygon information

`setPolygonInfo()`: Set new spatial polygon information

`getFeatureInfo()`: Gets spatial feature information

`setFeatureInfo()`: Sets new spatial feature information

`getSpatialEnrichment()`: Gets spatial enrichment information

`setSpatialEnrichment()`: Sets new spatial enrichment information

`getMultiomics()`: Gets multiomics information

`setMultiomics()`: Sets multiomics information


